# One-time setup helper: produces the Unity activation file (.alf) needed to
# create the UNITY_LICENSE secret for the "Unity verify" workflow.
#
# Run this once (Actions tab -> "Request Unity activation file" -> Run workflow),
# download the `activation-file` artifact, upload the .alf at
# https://license.unity3d.com/manual, download the resulting .ulf, and paste
# its entire contents as a repository secret named UNITY_LICENSE
# (repo Settings -> Secrets and variables -> Actions -> New repository secret).
name: Request Unity activation file

on:
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-request-activation-file@v2
      - uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: game-ci-alf
